# Generated by Django 4.1.4 on 2023-01-29 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyTogetherBody', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyTogetherBody.topic'),
        ),
    ]
